# Site settings
title: Made by Dale
email: dalemartyn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog covering Web, Technology, and Design by Dale.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dalemartyn.com" # the base hostname & protocol for your site
twitter_username: dalemartyn87
github_username:  dalemartyn

# Build settings
markdown: kramdown
highlighter: pygments
exclude: [node_modules, gulpfile.js, Gemfile, Gemfile.lock, .editorconfig,
          package.json, firebase.json, database.rules.json, firebase-debug.log]

# octopress
# Default extension for new posts and pages
post_ext: md
page_ext: html

post_dirs: false
permalink: /:categories/:title

# Format titles with titlecase?
titlecase: false

# Change default template file (in _templates/)
post_template: post
page_template: post
draft_template: draft
